import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "./components/navbar/navbar.jsx"
import Product from './components/product/product'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todolist',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        {children}
        
        </body>
    </html>
  )
}
